2018-05-17 17:34:41,416 ERROR [ERROR]: Caught exception in the launcher.
2018-05-17 17:34:41,422 ERROR [ERROR]: !=== Caught a fatal exception: ===!
2018-05-17 17:34:41,422 ERROR [ERROR]: Exception: 
'NoneType' object has no attribute 'value'
  File "C:/Users/Ian/Documents/GitHub/Terra/launcher.py", line 9, in <module>
    Main().run()

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\main.py", line 208, in run
    self.step(event)

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\main.py", line 146, in step
    EVENT_BUS.invoke_handlers(event)

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\event\eventbus.py", line 53, in invoke_handlers
    raise exc[0].with_traceback(exc[1], exc[2])

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\event\eventbus.py", line 50, in invoke_handlers
    handler(event)

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\main.py", line 103, in handle_menu_selections
    self.set_screen_from_mode(Mode.CAMPAIGN, event.mapname, map_type=AssetType.CAMPAIGN_MAP)

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\main.py", line 62, in set_screen_from_mode
    new_screen = BattleScreen(create_session=True)

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\screens\battlescreen.py", line 19, in __init__
    Session.set_up_local_game(map_name, map_type)

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\managers\session.py", line 39, in set_up_local_game
    bitmap, pieces, teams, upgrades, meta = load_map_from_file(map_name, map_type)

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\map\maputils.py", line 83, in load_map_from_file
    map_path = get_asset(asset_type, mapname)

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\resources\assetloading.py", line 24, in get_asset
    return str(Path(ROOT_DIR, asset_type.value))

2018-05-17 17:35:52,073 WARNING [WARN]: Caught exception while sending message 'b'[TEAM_FI][RED]None''. Retry 2 of 3.
2018-05-17 17:35:52,073 WARNING [WARN]: Caught exception while sending message 'b'[TEAM_FI][RED]None''. Retry 3 of 3.
2018-05-17 17:36:09,795 WARNING [WARN]: Caught exception while sending message 'b'[TEAM_FI][RED]None''. Retry 2 of 3.
2018-05-17 17:36:09,795 WARNING [WARN]: Caught exception while sending message 'b'[TEAM_FI][RED]None''. Retry 3 of 3.
2018-05-17 17:40:04,579 WARNING [WARN]: Caught exception while sending message 'b'[TEAM_FI][RED]None''. Retry 2 of 3.
2018-05-17 17:40:04,579 WARNING [WARN]: Caught exception while sending message 'b'[TEAM_FI][RED]None''. Retry 3 of 3.
2018-05-17 17:40:25,510 WARNING [WARN]: Caught exception while sending message 'b'[TEAM_FI][RED]None''. Retry 2 of 3.
2018-05-17 17:40:25,510 WARNING [WARN]: Caught exception while sending message 'b'[TEAM_FI][RED]None''. Retry 3 of 3.
2018-05-17 17:40:28,395 WARNING [WARN]: Caught exception while sending message 'b'[TEAM_FI][RED]None''. Retry 2 of 3.
2018-05-17 17:40:28,396 WARNING [WARN]: Caught exception while sending message 'b'[TEAM_FI][RED]None''. Retry 3 of 3.
2018-05-17 17:43:17,323 WARNING [WARN]: Caught exception while sending message 'b'[TEAM_FI][RED]None''. Retry 2 of 3.
2018-05-17 17:43:17,324 WARNING [WARN]: Caught exception while sending message 'b'[TEAM_FI][RED]None''. Retry 3 of 3.
2018-05-17 17:43:20,767 WARNING [WARN]: Caught exception while sending message 'b'[TEAM_FI][RED]None''. Retry 2 of 3.
2018-05-17 17:43:20,767 WARNING [WARN]: Caught exception while sending message 'b'[TEAM_FI][RED]None''. Retry 3 of 3.
2018-05-17 17:43:24,977 ERROR [ERROR]: Caught exception in the launcher.
2018-05-17 17:43:24,978 ERROR [ERROR]: !=== Caught a fatal exception: ===!
2018-05-17 17:43:24,979 ERROR [ERROR]: Exception: 
video system not initialized
  File "C:/Users/Ian/Documents/GitHub/Terra/launcher.py", line 9, in <module>
    Main().run()

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\main.py", line 218, in run
    self.step(event)

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\main.py", line 153, in step
    INPUT_CONTROLLER.invoke_handlers(event)

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\control\inputcontroller.py", line 57, in invoke_handlers
    handler()

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\menu\menu.py", line 105, in set_cursor_pos_to_mouse_coords
    if self.cursor_in_menu_bounds():

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\menu\menu.py", line 98, in cursor_in_menu_bounds
    mouse_x = get_pos()[0] / SETTINGS.get(Setting.SCREEN_SCALE)

2018-05-17 17:48:50,564 WARNING [WARN]: Caught exception while sending message 'b'[TEAM_FI][RED]None''. Retry 2 of 3.
2018-05-17 17:48:50,565 WARNING [WARN]: Caught exception while sending message 'b'[TEAM_FI][RED]None''. Retry 3 of 3.
2018-05-17 17:49:10,906 WARNING [WARN]: Caught exception while sending message 'b'[TEAM_FI][RED]None''. Retry 2 of 3.
2018-05-17 17:49:10,906 WARNING [WARN]: Caught exception while sending message 'b'[TEAM_FI][RED]None''. Retry 3 of 3.
2018-05-17 17:49:14,399 WARNING [WARN]: Caught exception while sending message 'b'[TEAM_FI][RED]None''. Retry 2 of 3.
2018-05-17 17:49:14,399 WARNING [WARN]: Caught exception while sending message 'b'[TEAM_FI][RED]None''. Retry 3 of 3.
2018-05-17 17:50:46,730 WARNING [WARN]: Caught exception while sending message 'b'[TEAM_FI][RED]None''. Retry 2 of 3.
2018-05-17 17:50:46,730 WARNING [WARN]: Caught exception while sending message 'b'[TEAM_FI][RED]None''. Retry 3 of 3.
2018-05-17 17:51:17,671 WARNING [WARN]: Caught exception while sending message 'b'[TEAM_FI][RED]None''. Retry 2 of 3.
2018-05-17 17:51:17,671 WARNING [WARN]: Caught exception while sending message 'b'[TEAM_FI][RED]None''. Retry 3 of 3.
2018-05-17 17:52:15,874 WARNING [WARN]: Caught exception while sending message 'b'[TEAM_FI][RED]None''. Retry 2 of 3.
2018-05-17 17:52:15,874 WARNING [WARN]: Caught exception while sending message 'b'[TEAM_FI][RED]None''. Retry 3 of 3.
2018-05-17 17:52:24,554 WARNING [WARN]: Caught exception while sending message 'b'[TEAM_FI][RED]None''. Retry 2 of 3.
2018-05-17 17:52:24,554 WARNING [WARN]: Caught exception while sending message 'b'[TEAM_FI][RED]None''. Retry 3 of 3.
2018-05-17 18:03:14,689 ERROR [ERROR]: Caught exception in the launcher.
2018-05-17 18:03:14,694 ERROR [ERROR]: !=== Caught a fatal exception: ===!
2018-05-17 18:03:14,695 ERROR [ERROR]: Exception: 
unhashable type: 'list'
  File "C:/Users/Ian/Documents/GitHub/Terra/launcher.py", line 9, in <module>
    Main().run()

  File "C:/Users/Ian/Documents/GitHub/Terra\terra\main.py", line 35, in __init__
    self.set_screen_from_mode(Mode.MAIN_MENU)

  File "C:/Users/Ian/Documents/GitHub/Terra\terra\main.py", line 57, in set_screen_from_mode
    new_screen = TitleScreen()

  File "C:/Users/Ian/Documents/GitHub/Terra\terra\screens\titlescreen.py", line 16, in __init__
    self.main_menu = MainMenu()

  File "C:/Users/Ian/Documents/GitHub/Terra\terra\menu\mainmenu.py", line 105, in __init__
    self.current_menu = generate_menu()

  File "C:/Users/Ian/Documents/GitHub/Terra\terra\menu\mainmenu.py", line 44, in generate_menu
    (Option.CAMPAIGN, generate_campaign_menu()),

  File "C:/Users/Ian/Documents/GitHub/Terra\terra\menu\mainmenu.py", line 89, in generate_campaign_menu
    open_maps = [mapname for mapname in loadable_maps if mapname in completed_maps]

  File "C:/Users/Ian/Documents/GitHub/Terra\terra\menu\mainmenu.py", line 89, in <listcomp>
    open_maps = [mapname for mapname in loadable_maps if mapname in completed_maps]

2018-05-17 18:09:19,725 WARNING [WARN]: Caught exception while sending message 'b'[TEAM_FI][RED]None''. Retry 2 of 3.
2018-05-17 18:09:19,725 WARNING [WARN]: Caught exception while sending message 'b'[TEAM_FI][RED]None''. Retry 3 of 3.
2018-05-17 18:12:15,158 WARNING [WARN]: Caught exception while sending message 'b'[TEAM_FI][RED]None''. Retry 2 of 3.
2018-05-17 18:12:15,159 WARNING [WARN]: Caught exception while sending message 'b'[TEAM_FI][RED]None''. Retry 3 of 3.
2018-05-17 18:12:24,284 WARNING [WARN]: Caught exception while sending message 'b'[TEAM_FI][RED]None''. Retry 2 of 3.
2018-05-17 18:12:24,284 WARNING [WARN]: Caught exception while sending message 'b'[TEAM_FI][RED]None''. Retry 3 of 3.
2018-05-17 18:13:36,204 WARNING [WARN]: Caught exception while sending message 'b'[TEAM_FI][RED]None''. Retry 2 of 3.
2018-05-17 18:13:36,204 WARNING [WARN]: Caught exception while sending message 'b'[TEAM_FI][RED]None''. Retry 3 of 3.
2018-05-17 18:17:34,024 WARNING [WARN]: Caught exception while sending message 'b'[TEAM_FI][RED]None''. Retry 2 of 3.
2018-05-17 18:17:34,024 WARNING [WARN]: Caught exception while sending message 'b'[TEAM_FI][RED]None''. Retry 3 of 3.
2018-05-17 18:18:51,146 WARNING [WARN]: Caught exception while sending message 'b'[TEAM_FI][RED]None''. Retry 2 of 3.
2018-05-17 18:18:51,146 WARNING [WARN]: Caught exception while sending message 'b'[TEAM_FI][RED]None''. Retry 3 of 3.
2018-05-17 18:19:47,767 WARNING [WARN]: Caught exception while sending message 'b'[TEAM_FI][RED]None''. Retry 2 of 3.
2018-05-17 18:19:47,767 WARNING [WARN]: Caught exception while sending message 'b'[TEAM_FI][RED]None''. Retry 3 of 3.
2018-05-17 18:20:21,986 WARNING [WARN]: Caught exception while sending message 'b'[TEAM_FI][RED]None''. Retry 2 of 3.
2018-05-17 18:20:21,987 WARNING [WARN]: Caught exception while sending message 'b'[TEAM_FI][RED]None''. Retry 3 of 3.
2018-05-17 18:20:33,456 WARNING [WARN]: Caught exception while sending message 'b'[TEAM_FI][RED]None''. Retry 2 of 3.
2018-05-17 18:20:33,456 WARNING [WARN]: Caught exception while sending message 'b'[TEAM_FI][RED]None''. Retry 3 of 3.
2018-05-17 18:20:34,275 ERROR [ERROR]: Caught exception in the launcher.
2018-05-17 18:20:34,275 ERROR [ERROR]: !=== Caught a fatal exception: ===!
2018-05-17 18:20:34,275 ERROR [ERROR]: Exception: 
must have exactly one of create/read/write/append mode
  File "C:/Users/Ian/Documents/GitHub/Terra/launcher.py", line 9, in <module>
    Main().run()

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\main.py", line 208, in run
    self.step(event)

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\main.py", line 146, in step
    EVENT_BUS.invoke_handlers(event)

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\event\eventbus.py", line 53, in invoke_handlers
    raise exc[0].with_traceback(exc[1], exc[2])

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\event\eventbus.py", line 50, in invoke_handlers
    handler(event)

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\managers\campaignmanager.py", line 24, in handle_battle_end
    save_campaign_progress(self.get_map_name())

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\managers\campaignmanager.py", line 62, in save_campaign_progress
    with open(progress_path, 'wr') as progress_file:

2018-05-17 18:21:25,604 WARNING [WARN]: Caught exception while sending message 'b'[TEAM_FI][RED]None''. Retry 2 of 3.
2018-05-17 18:21:25,604 WARNING [WARN]: Caught exception while sending message 'b'[TEAM_FI][RED]None''. Retry 3 of 3.
2018-05-17 18:23:02,746 WARNING [WARN]: Caught exception while sending message 'b'[TEAM_FI][RED]None''. Retry 2 of 3.
2018-05-17 18:23:02,746 WARNING [WARN]: Caught exception while sending message 'b'[TEAM_FI][RED]None''. Retry 3 of 3.
2018-05-17 18:23:05,892 WARNING [WARN]: Caught exception while sending message 'b'[TEAM_FI][RED]None''. Retry 2 of 3.
2018-05-17 18:23:05,893 WARNING [WARN]: Caught exception while sending message 'b'[TEAM_FI][RED]None''. Retry 3 of 3.
2018-05-17 18:23:08,704 WARNING [WARN]: Caught exception while sending message 'b'[TEAM_FI][RED]None''. Retry 2 of 3.
2018-05-17 18:23:08,704 WARNING [WARN]: Caught exception while sending message 'b'[TEAM_FI][RED]None''. Retry 3 of 3.
2018-05-17 18:39:11,906 WARNING [WARN]: Caught exception while sending message 'b'[TEAM_FI][RED]None''. Retry 2 of 3.
2018-05-17 18:39:11,906 WARNING [WARN]: Caught exception while sending message 'b'[TEAM_FI][RED]None''. Retry 3 of 3.
2018-05-17 18:39:17,213 WARNING [WARN]: Caught exception while sending message 'b'[TEAM_FI][RED]None''. Retry 2 of 3.
2018-05-17 18:39:17,213 WARNING [WARN]: Caught exception while sending message 'b'[TEAM_FI][RED]None''. Retry 3 of 3.
2018-05-17 18:39:20,508 WARNING [WARN]: Caught exception while sending message 'b'[TEAM_FI][RED]None''. Retry 2 of 3.
2018-05-17 18:39:20,508 WARNING [WARN]: Caught exception while sending message 'b'[TEAM_FI][RED]None''. Retry 3 of 3.
