2018-04-16 18:45:15,065 ERROR [ERROR]: Caught exception in the launcher.
2018-04-16 18:45:15,066 ERROR [ERROR]: !=== Caught a fatal exception: ===!
2018-04-16 18:45:15,066 ERROR [ERROR]: Exception: 
list index out of range
  File "C:/Users/Ian/Documents/GitHub/Terra/launcher.py", line 8, in <module>
    Main().run()

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\main.py", line 199, in run
    self.render()

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\main.py", line 156, in render
    game_screen = self.current_screen.render(ui_screen)

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\menu\titlescreen.py", line 39, in render
    self.main_menu.render(game_screen, ui_screen)

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\menu\mainmenu.py", line 244, in render
    map_preview = draw_map_preview_from_file(container_width, container_height, option[0], asset_type=asset_type)

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\map\minimap.py", line 93, in draw_map_preview_from_file
    return draw_map_preview(container_width, container_height, bitmap, pieces, teams)

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\map\minimap.py", line 61, in draw_map_preview
    minimap = generate_minimap(bitmap, pieces)

  File "C:\Users\Ian\Documents\GitHub\Terra\terra\map\minimap.py", line 16, in generate_minimap
    width = len(bitmap[0])

2018-04-16 18:45:46,871 WARNING [WARN]: Caught exception while sending message 'b'[TEAM_FI][RED]None''. Retry 2 of 3.
2018-04-16 18:45:46,871 WARNING [WARN]: Caught exception while sending message 'b'[TEAM_FI][RED]None''. Retry 3 of 3.
